const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  DELETE_TOKEN: "DELETE_TOKEN",
  GET_STUDENT: "GET_STUDENT",
  DELETE: "DELETE",
  GET_ALL_STUDENTS: "GET_ALL_STUDENTS",
};

export default ACTIONS;
